const cameraFeateures = {
  "ISO Range": " ",
  Processor: " ",
  "Sensor Type": " ",
  "LCD Screen Size": " ",
  "Video Recording": " ",
  "Viewfinder Type": " ",
  "Autofocus System": " ",
  "Sensor Resolution": " ",
  "Image Stabilization": " ",
  "Shutter Speed Range": " ",
  "LCD Screen Resolution": " ",
  "Continuous Shooting Speed": " ",
};

const cameraDetails = {
  "Hot Shoe": " ",
  "Built-in GPS": " ",
  "Video Output": " ",
  "Built-in Flash": " ",
  "Headphone Jack": " ",
  "Weather Sealing": " ",
  "Autofocus Points": " ",
  "Microphone Input": " ",
  "Exposure Metering": " ",
  "Shutter Durability": " ",
  "Viewfinder Coverage": " ",
  "In-camera Image Editing": " ",
  "Viewfinder Magnification": " ",
};

const mobileFeatures = {
  RAM: " ",
  Battery: " ",
  Storage: " ",
  Processor: " ",
  Resolution: " ",
  "Rear Camera": " ",
  "Screen Size": " ",
  "Front Camera": " ",
  "Operating System": " ",
};

const mobileDetails = {
  GPS: " ",
  GPU: " ",
  Audio: " ",
  Weight: " ",
  Sensors: " ",
  Charging: " ",
  "SIM Type": " ",
  Dimensions: " ",
  "Face Unlock": " ",
  "Battery Life": " ",
  "Battery Type": " ",
  Connectivity: " ",
  "Display Type": " ",
  "Processor Speed": " ",
  "Video Recording": " ",
  "Display Resolution": " ",
  "Expandable Storage": " ",
  "Fingerprint Sensor": " ",
  "Additional Features": " ",
  "Fast Charging Support": " ",
  "Internal Storage Type": " ",
  "Manufacturer Warranty": " ",
  "Biometric Authentication": " ",
  "Operating System Version": " ",
  "Water and Dust Resistance": " ",
};

const laptopFeatures = {
  RAM: " ",
  Battery: " ",
  Storage: " ",
  Graphics: " ",
  Processor: " ",
  Resolution: " ",
  "Screen Size": " ",
  "Operating System": " ",
};

const LaptopDetails = {
  GPU: " ",
  Audio: " ",
  Color: " ",
  Ports: " ",
  Camera: " ",
  Weight: " ",
  Sensors: " ",
  Warranty: " ",
  Dimensions: " ",
  "Screen Type": " ",
  Touchscreen: " ",
  Connectivity: " ",
  "Storage Type": " ",
  "Keyboard Layout": " ",
  "Processor Speed": " ",
  "Display Resolution": " ",
  "Wireless Technology": " ",
  "Biometric Authentication": " ",
};

